name: face_authentication_app
description: A modern Flutter face authentication application with advanced biometric security.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Camera and ML
  camera: ^0.11.0+1
  google_ml_kit: ^0.18.0
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  
  # Database and Storage
  sqflite: ^2.4.0
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.3.0
  path_provider: ^2.1.4
  
  # Security and Crypto
  crypto: ^3.0.5
  permission_handler: ^11.3.1
  
  # UI and Animation
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/animations/
  #   - assets/images/