name: face_authentication_app
description: A modern Flutter face authentication application with advanced biometric security.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Camera and ML - Updated to compatible versions
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.9.0
  image: ^4.1.7
  
  # Database and Storage
  sqflite: ^2.3.3+1
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # Security and Crypto
  crypto: ^3.0.3
  permission_handler: ^11.3.1
  
  # UI and Animation
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true